{
 "title": "TPA",
 "time": { "from": "2023-12-27T14:06:09.281Z", "to": "2023-12-28T02:06:09.281Z" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Corrélation entre le revenu et le prix des voitures (0-1000€)",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  cu.income AS customer_income,\r\n  AVG(c.price) AS avg_car_price\r\nFROM\r\n  catalog_car c\r\n  JOIN customer_car_registration r ON c.id = r.car_id\r\n  JOIN customer cu ON r.registration_id = cu.current_registration_id\r\nWHERE\r\n  cu.income >= 0 AND cu.income <= 1000\r\nGROUP BY\r\n  cu.income\r\nORDER BY\r\n  cu.income;\r\n"
    }
   ]
  },
  {
   "title": "Corrélation entre le revenu et le prix des voitures (1001-2200€)",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  cu.income AS customer_income,\r\n  AVG(c.price) AS avg_car_price\r\nFROM\r\n  catalog_car c\r\n  JOIN customer_car_registration r ON c.id = r.car_id\r\n  JOIN customer cu ON r.registration_id = cu.current_registration_id\r\nWHERE\r\n  cu.income > 1000 AND cu.income <= 2200\r\nGROUP BY\r\n  cu.income\r\nORDER BY\r\n  cu.income;\r\n"
    }
   ]
  },
  {
   "title": "Corrélation entre le revenu et le prix des voitures (2201€+)",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  cu.income AS customer_income,\r\n  AVG(c.price) AS avg_car_price\r\nFROM\r\n  catalog_car c\r\n  JOIN customer_car_registration r ON c.id = r.car_id\r\n  JOIN customer cu ON r.registration_id = cu.current_registration_id\r\nWHERE\r\n  cu.income > 2200\r\nGROUP BY\r\n  cu.income\r\nORDER BY\r\n  cu.income;\r\n"
    }
   ]
  },
  {
   "title": "Puissance moyenne et émissions de CO2",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "g/km" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT cc.power AS avg_power , bce.co2_emissions AS avg_co2_emissions\r\nFROM catalog_car cc\r\nJOIN brand_co2_emissions bce ON cc.brand = bce.brand;"
    }
   ]
  },
  {
   "title": "Répartition des prix des voitures par marque",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "voitures" } },
   "targets": [
    {
     "rawSql": "SELECT brand, COUNT(*) AS car_count, AVG(price) AS avg_price, MIN(price) AS min_price, MAX(price) AS max_price\r\nFROM catalog_car\r\nGROUP BY brand;"
    }
   ]
  },
  {
   "title": "Top 5 des marques de voitures les plus immatriculées",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "voitures" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT c.brand, COUNT(*) AS registration_count\r\nFROM catalog_car c\r\nJOIN customer_car_registration r ON c.id = r.car_id\r\nGROUP BY c.brand\r\nORDER BY registration_count DESC\r\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Relation entre le prix des voitures et les émissions de CO2 par marque",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT cc.brand, AVG(cc.price) AS avg_price, AVG(bce.co2_emissions) AS avg_co2_emissions, COUNT(*) AS car_count\r\nFROM catalog_car cc\r\nJOIN brand_co2_emissions bce ON cc.brand = bce.brand\r\nGROUP BY cc.brand;\r\n"
    }
   ]
  },
  {
   "title": "Revenu moyen et âge par marque de voiture",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Ans" } },
   "targets": [
    {
     "rawSql": "SELECT c.brand, AVG(cu.income) AS avg_income, AVG(cu.age) AS avg_age\r\nFROM catalog_car c\r\nJOIN customer_car_registration r ON c.id = r.car_id\r\nJOIN customer cu ON r.registration_id = cu.current_registration_id\r\nGROUP BY c.brand\r\nORDER BY avg_income DESC;\r\n"
    }
   ]
  },
  {
   "title": "Immatriculation des voitures avec le nombre de places assises et le nombre de portes",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT cc.seating_capacity, cc.number_doors, COUNT(*) AS registration_count\r\nFROM catalog_car cc\r\nJOIN customer_car_registration ccr ON cc.id = ccr.car_id\r\nGROUP BY cc.seating_capacity, cc.number_doors;"
    }
   ]
  },
  {
   "title": "Marques de voitures avec la puissance moyenne la plus élevée",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ch" } },
   "targets": [
    {
     "rawSql": "SELECT cc.brand, AVG(cc.power) AS avg_power\r\nFROM catalog_car cc\r\nGROUP BY cc.brand\r\nORDER BY avg_power DESC;"
    }
   ]
  },
  { "title": "Emissions de CO2 Marque", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Nombre total de voitures par marque",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT brand, COUNT(*) FROM brand_co2_emissions GROUP BY brand ORDER BY COUNT(*) DESC "
    }
   ]
  },
  {
   "title": "Émissions de CO2 moyennes par marque",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "g/km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT brand, AVG(co2_emissions) FROM brand_co2_emissions WHERE co2_emissions > 0 GROUP BY brand ORDER BY AVG(co2_emissions) "
    }
   ]
  },
  {
   "title": "Coût moyen de l'énergie par marque de voiture",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT brand, AVG(energy_cost) AS avg_energy_cost\r\nFROM brand_co2_emissions\r\nGROUP BY brand\r\nORDER BY avg_energy_cost DESC;\r\n"
    }
   ]
  },
  {
   "title": "Distribution des valeurs de bonus/malus",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE \r\n        WHEN bonus_malus >= 0 THEN 'B'\r\n        WHEN bonus_malus < 0 THEN 'M'\r\n        ELSE 'N'\r\n    END AS bonus_malus_category,\r\n    COUNT(*) AS count\r\nFROM brand_co2_emissions\r\nGROUP BY bonus_malus_category;\r\n"
    }
   ]
  },
  {
   "title": "Top 3 des modèles de voitures ayant les coûts énergétiques les plus bas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "g/km CO2" } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(brand, ' ', car_name) AS brand_car_name, energy_cost\r\nFROM brand_co2_emissions\r\nORDER BY energy_cost ASC\r\nLIMIT 3;"
    }
   ]
  },
  {
   "title": "Répartition des émissions de CO2",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "g/km" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE \r\n        WHEN co2_emissions >= 0 AND co2_emissions <= 100 THEN '0-100'\r\n        WHEN co2_emissions > 100 AND co2_emissions <= 200 THEN '101-200'\r\n        WHEN co2_emissions > 200 AND co2_emissions <= 300 THEN '201-300'\r\n        WHEN co2_emissions > 300 AND co2_emissions <= 400 THEN '301-400'\r\n        WHEN co2_emissions > 400 AND co2_emissions <= 500 THEN '301-400'\r\n        WHEN co2_emissions > 500 THEN '500+'\r\n        ELSE 'N'\r\n    END AS co2_emissions_range,\r\n    COUNT(*) AS count\r\nFROM brand_co2_emissions\r\nWHERE co2_emissions IS NOT NULL\r\nGROUP BY co2_emissions_range\r\nORDER BY co2_emissions_range;\r\n"
    }
   ]
  },
  {
   "title": "Rapport bonus/malus par marque de voiture",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT brand, COUNT(bonus_malus) AS with_bonus_malus\r\nFROM brand_co2_emissions\r\nGROUP BY brand\r\nORDER BY with_bonus_malus;"
    }
   ]
  },
  {
   "title": "Top 3 des modèles de voitures ayant les coûts énergétiques les plus élevés",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "g/km" } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(brand, ' ', car_name) AS brand_car_name, energy_cost\r\nFROM brand_co2_emissions\r\nORDER BY energy_cost DESC\r\nLIMIT 3;"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Nombre de clients par tranche d'âge et genre",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN cu.age BETWEEN 18 AND 25 THEN '18-25'\r\n    WHEN cu.age BETWEEN 26 AND 35 THEN '26-35'\r\n    WHEN cu.age BETWEEN 36 AND 45 THEN '36-45'\r\n    ELSE '46+'\r\n  END as age_group,\r\n  COUNT(*) FILTER (WHERE cu.gender = 'M') as male_customers,\r\n  COUNT(*) FILTER (WHERE cu.gender = 'F') as female_customers\r\nFROM customer AS cu\r\nGROUP BY age_group;\r\n"
    }
   ]
  },
  {
   "title": "Nombre de clients possédant une deuxième voiture par genre",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  cu.has_second_car,\r\n  COUNT(*) FILTER (WHERE cu.gender = 'M') as male_customers,\r\n  COUNT(*) FILTER (WHERE cu.gender = 'F') as female_customers\r\nFROM customer AS cu\r\nGROUP BY cu.has_second_car;\r\n"
    }
   ]
  },
  {
   "title": "Nombre de clients par statut marital et genre",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  cu.marital_status,\r\n  COUNT(*) FILTER (WHERE cu.gender = 'M') as male_customers,\r\n  COUNT(*) FILTER (WHERE cu.gender = 'F') as female_customers\r\nFROM\r\n  customer AS cu\r\nGROUP BY\r\n  cu.marital_status;\r\n"
    }
   ]
  },
  {
   "title": "Taux d'endettement moyen par revenue",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  income,\r\n  AVG(debt_rate) AS avg_debt_rate\r\nFROM\r\n  customer\r\nGROUP BY\r\n  income\r\nORDER BY\r\n  income;\r\n"
    }
   ]
  },
  {
   "title": "Répartition des clients par âge",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT age, COUNT(*) AS count\r\nFROM customer\r\nGROUP BY age;\r\n"
    }
   ]
  },
  {
   "title": "Nombre d'enfants à charge Répartition",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT dependent_children, COUNT(*) AS count\r\nFROM customer\r\nGROUP BY dependent_children;"
    }
   ]
  },
  {
   "title": "Composition par sexe",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN gender = 'F' THEN 'Femme'\r\n    WHEN gender = 'M' THEN 'Homme'\r\n    ELSE 'Autre'\r\n  END AS gender_format,\r\n  COUNT(*) AS count\r\nFROM customer\r\nGROUP BY gender_format;\r\n"
    }
   ]
  },
  {
   "title": "Revenu moyen par statut marital",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT marital_status, AVG(income) AS avg_income\r\nFROM customer\r\nGROUP BY marital_status;"
    }
   ]
  },
  { "title": "Catalogue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Nombre de voitures par couleur",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "voitures" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) as total_cars,\r\n  c.color\r\nFROM\r\n  catalog_car AS c\r\nGROUP BY\r\n  c.color;\r\n"
    }
   ]
  },
  {
   "title": "Répartition des prix des voitures par couleur",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 3, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cc.color, AVG(cc.price) AS avg_price\r\nFROM catalog_car cc\r\nGROUP BY cc.color\r\nORDER BY cc.color;\r\n"
    }
   ]
  },
  {
   "title": "Distribution de la puissance dans les voitures",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 67 },
   "targets": [
    {
     "rawSql": "SELECT power, COUNT(*) AS car_count\r\nFROM catalog_car\r\nGROUP BY power\r\nORDER BY power;"
    }
   ]
  },
  {
   "title": "Relation entre la puissance et les émissions de CO2",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 67 },
   "targets": [
    {
     "rawSql": "SELECT power, AVG(co2_emissions) AS avg_co2_emissions, AVG(price) AS avg_price\r\nFROM catalog_car\r\nGROUP BY power;"
    }
   ]
  },
  {
   "title": "Les 5 voitures les plus longues et avec leur place assise",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "sieges" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT name, length, seating_capacity\r\nFROM catalog_car\r\nORDER BY length DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  { "title": "Marketing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Répartition des tranches d'âges dans les données de marketing",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN age BETWEEN 18 AND 25 THEN '18-25 ans'\r\n    WHEN age BETWEEN 26 AND 35 THEN '26-35 ans'\r\n    WHEN age BETWEEN 36 AND 45 THEN '36-45 ans'\r\n    ELSE '46+ ans'\r\n  END AS age_group,\r\n  COUNT(*) AS count\r\nFROM customer_marketing\r\nGROUP BY age_group\r\nORDER BY age_group;\r\n"
    }
   ]
  },
  {
   "title": "Répartition des sexes dans le secteur du marketing",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT gender, COUNT(*) AS count\r\nFROM customer_marketing\r\nGROUP BY gender;\r\n"
    }
   ]
  },
  {
   "title": "Répartition des enfants à charge dans le marketing",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT dependent_children, COUNT(*) AS count\r\nFROM customer_marketing\r\nGROUP BY dependent_children\r\nORDER BY dependent_children;"
    }
   ]
  },
  {
   "title": "Répartition des clients par fourchette de taux d'endettement dans le secteur du marketing",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT ROUND(debt_rate / 100) * 100 AS debt_range, COUNT(*) AS count\r\nFROM customer_marketing\r\nGROUP BY debt_range\r\nORDER BY debt_range;"
    }
   ]
  },
  {
   "title": "Top 5 des groupes d'âge ayant les revenus les plus élevés en marketing",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT age, MAX(income) AS max_income\r\nFROM customer_marketing\r\nGROUP BY age\r\nORDER BY max_income DESC\r\nLIMIT 5;\r\n"
    }
   ]
  }
 ]
}