sql:
  connectionString: postgres://postgres:AglaeSebastien@135.181.84.87:5432/mbds_bigdata?sslmode=disable
nats:
  url: nats://135.181.84.87:4222
connector:
  event:
    stream: DATASOURCE
    consumer:
      new: NEW
      update: UPDATE
      upsert: UPSERT
      delete: DELETE
  database: mbds_bigdata
